# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 02:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_index', models.CharField(max_length=20)),
                ('location_easting_osgr', models.IntegerField()),
                ('location_northing_osgr', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('police_force', models.IntegerField()),
                ('accident_severity', models.IntegerField()),
                ('number_of_vehicles', models.IntegerField()),
                ('number_of_casualties', models.IntegerField()),
                ('date', models.DateField()),
                ('day_of_week', models.IntegerField()),
                ('time', models.TimeField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=27700)),
            ],
        ),
    ]
